# prefix C for catalyst. each letter used is not important, just labels
CA = 'EC:4.3.1.24'
CB = 'EC:4.3.1.25'
CC = 'EC:1.14.14.91'
CD = 'EC:6.2.1.12'
CE = 'EC:2.3.1.170'
CF = 'EC:2.3.1.133'
CG = 'EC:1.14.14.96'
CH = 'EC:1.14.13.-'
CI = 'EC:2.3.1.74'
CJ = 'EC:5.5.1.6'
CK = 'EC:1.14.20.5'
CL = 'EC:1.14.19.76'
CM = 'EC:1.14.14.81'
CN = 'EC:1.14.14.82'
CO = 'EC:1.14.11.9'
CP = 'EC:1.14.20.6'
CQ = 'EC:1.1.12.19'
CR = 'EC:1.14.20.4'
CS = 'EC:1.3.1.77'
CT = 'EC:1.17.1.3'
CU = 'EC:1.14.14.87'
CV = 'EC:4.2.1.105'
logic_ec1 = 'EC:2.4.1.74'
logic_ec2 = 'EC:2.3.1.70'
logic_ec3 = 'EC:2.3.1.30'
logic_ec4 = 'EC:2.4.1.136'

# logical combination of pathways for each chemical
start = (CA or CB) and CC and CD

logic_nari = start and CI and CJ
logic_erio = (logic_nari and (CM or CN)) or (CH or (CF and CG) and CI)
logic_kaem = logic_nari and CO and CP
logic_quer = logic_erio and ((CO and CP) or (logic_kaem and (CM or CN)))
logic_cate = logic_erio and CO and CQ and CT
logic_gall = logic_erio and CO and CM and CQ and CT
logic_epig = logic_erio and CO and CM and CQ and CR and CS
logic_cyan = logic_erio and CO and CQ and CR
logic_ecat = logic_cyan and CS
logic_myri = (logic_quer and CM) or (logic_erio and CM and CP) or (logic_nari and CO and (CM or CN) and CM and CP)
isoflavonoid = start and CE and CJ
logic_apig = ((CK or CL) and logic_nari) or (isoflavonoid and (CK or CL))
logic_lute = logic_apig and (CM or CN)
logic_geni = isoflavonoid and CU and CV
logic_liqu = isoflavonoid
logic_isol = logic_liqu and CJ
logic_bute = (start and CE) or logic_isol

APIG = 'Apigenin'
BUTE = 'Butein'
CATE = 'Catechin'
CYAN = 'Cyanidin'
ECAT = 'Epicatechin'
EPIG = 'Epigallocatechin'
ERIO = 'Eriodictyol'
GALL = 'Gallocatechin'
GENI = 'Genistein'
KAEM = 'Kaempferol'
LUTE = 'Luteolin'
MYRI = 'Myricetin'
NARI = 'Naringenin'
QUER = 'Quercetin'
