ENZ_A = 'EC:4.3.1.24'
ENZ_B = 'EC:4.3.1.25'
ENZ_C = 'EC:1.14.14.91'
ENZ_D = 'EC:6.2.1.12'
ENZ_E = 'EC:2.3.1.170'
ENZ_F = 'EC:2.3.1.133'
ENZ_G = 'EC:1.14.14.96'
ENZ_H = 'EC:1.14.13.-'
ENZ_I = 'EC:2.3.1.74'
ENZ_J = 'EC:5.5.1.6'
ENZ_K = 'EC:1.14.20.5'
ENZ_L = 'EC:1.14.19.76'
ENZ_M = 'EC:1.14.14.81'
ENZ_N = 'EC:1.14.14.82'
ENZ_O = 'EC:1.14.11.9'
ENZ_P = 'EC:1.14.20.6'
ENZ_Q = 'EC:1.1.12.19'
ENZ_R = 'EC:1.14.20.4'
ENZ_S = 'EC:1.3.1.77'
ENZ_T = 'EC:1.17.1.3'
ENZ_U = 'EC:1.14.14.87'
ENZ_V = 'EC:4.2.1.105'
ENZ_W = 'EC:2.4.1.74'
ENZ_X = 'EC:2.3.1.70'
ENZ_Y = 'EC:2.3.1.30'
ENZ_Z = 'EC:2.4.1.136'

# logical combination of pathways for each chemical
start = (ENZ_A or ENZ_B) and ENZ_C and ENZ_D

req_nari = start and ENZ_I and ENZ_J
req_erio = (req_nari and (ENZ_M or ENZ_N)) or (ENZ_H or (ENZ_F and ENZ_G) and ENZ_I)
req_kaem = req_nari and ENZ_O and ENZ_P
req_quer = req_erio and ((ENZ_O and ENZ_P) or (req_kaem and (ENZ_M or ENZ_N)))
req_cate = req_erio and ENZ_O and ENZ_Q and ENZ_T
req_gall = req_erio and ENZ_O and ENZ_M and ENZ_Q and ENZ_T
req_epig = req_erio and ENZ_O and ENZ_M and ENZ_Q and ENZ_R and ENZ_S
req_cyan = req_erio and ENZ_O and ENZ_Q and ENZ_R
req_ecat = req_cyan and ENZ_S
req_myri = (req_quer and ENZ_M) or (req_erio and ENZ_M and ENZ_P) or \
           (req_nari and ENZ_O and (ENZ_M or ENZ_N) and ENZ_M and ENZ_P)
req_isoflav = start and ENZ_E and ENZ_J
req_apig = ((ENZ_K or ENZ_L) and req_nari) or (req_isoflav and (ENZ_K or ENZ_L))
req_lute = req_apig and (ENZ_M or ENZ_N)
req_geni = req_isoflav and ENZ_U and ENZ_V
req_liqu = req_isoflav
req_isol = req_liqu and ENZ_J
req_bute = (start and (ENZ_E or 'KO:K08243')) or req_isol

APIG = 'Apigenin'
BUTE = 'Butein'
CATE = 'Catechin'
CYAN = 'Cyanidin'
ECAT = 'Epicatechin'
EPIG = 'Epigallocatechin'
ERIO = 'Eriodictyol'
GALL = 'Gallocatechin'
GENI = 'Genistein'
KAEM = 'Kaempferol'
LUTE = 'Luteolin'
MYRI = 'Myricetin'
NARI = 'Naringenin'
QUER = 'Quercetin'
