# prefix C for catalyst. each letter used is not important, just labels
ENZ_A = 'EC:4.3.1.24'
ENZ_B = 'EC:4.3.1.25'
ENZ_C = 'EC:1.14.14.91'
ENZ_D = 'EC:6.2.1.12'
ENZ_E = 'EC:2.3.1.170'
ENZ_F = 'EC:2.3.1.133'
ENZ_G = 'EC:1.14.14.96'
ENZ_H = 'EC:1.14.13.-'
ENZ_I = 'EC:2.3.1.74'
ENZ_J = 'EC:5.5.1.6'
ENZ_K = 'EC:1.14.20.5'
ENZ_L = 'EC:1.14.19.76'
ENZ_M = 'EC:1.14.14.81'
ENZ_N = 'EC:1.14.14.82'
ENZ_O = 'EC:1.14.11.9'
ENZ_P = 'EC:1.14.20.6'
ENZ_Q = 'EC:1.1.12.19'
ENZ_R = 'EC:1.14.20.4'
ENZ_S = 'EC:1.3.1.77'
ENZ_T = 'EC:1.17.1.3'
ENZ_U = 'EC:1.14.14.87'
ENZ_V = 'EC:4.2.1.105'
ENZ_W = 'EC:2.4.1.74'
ENZ_X = 'EC:2.3.1.70'
ENZ_Y = 'EC:2.3.1.30'
ENZ_Z = 'EC:2.4.1.136'

# logical combination of pathways for each chemical
start = (ENZ_A or ENZ_B) and ENZ_C and ENZ_D

logic_nari = start and ENZ_I and ENZ_J
logic_erio = (logic_nari and (ENZ_M or ENZ_N)) or (ENZ_H or (ENZ_F and ENZ_G) and ENZ_I)
logic_kaem = logic_nari and ENZ_O and ENZ_P
logic_quer = logic_erio and ((ENZ_O and ENZ_P) or (logic_kaem and (ENZ_M or ENZ_N)))
logic_cate = logic_erio and ENZ_O and ENZ_Q and ENZ_T
logic_gall = logic_erio and ENZ_O and ENZ_M and ENZ_Q and ENZ_T
logic_epig = logic_erio and ENZ_O and ENZ_M and ENZ_Q and ENZ_R and ENZ_S
logic_cyan = logic_erio and ENZ_O and ENZ_Q and ENZ_R
logic_ecat = logic_cyan and ENZ_S
logic_myri = (logic_quer and ENZ_M) or (logic_erio and ENZ_M and ENZ_P) or (logic_nari and ENZ_O and (ENZ_M or ENZ_N) and ENZ_M and ENZ_P)
isoflavonoid = start and ENZ_E and ENZ_J
logic_apig = ((ENZ_K or ENZ_L) and logic_nari) or (isoflavonoid and (ENZ_K or ENZ_L))
logic_lute = logic_apig and (ENZ_M or ENZ_N)
logic_geni = isoflavonoid and ENZ_U and ENZ_V
logic_liqu = isoflavonoid
logic_isol = logic_liqu and ENZ_J
logic_bute = (start and ENZ_E) or logic_isol

APIG = 'Apigenin'
BUTE = 'Butein'
CATE = 'Catechin'
CYAN = 'Cyanidin'
ECAT = 'Epicatechin'
EPIG = 'Epigallocatechin'
ERIO = 'Eriodictyol'
GALL = 'Gallocatechin'
GENI = 'Genistein'
KAEM = 'Kaempferol'
LUTE = 'Luteolin'
MYRI = 'Myricetin'
NARI = 'Naringenin'
QUER = 'Quercetin'
